### ISSUE TITLE
Work page

### ISSUE THREAD

**Issue by kelvinlockwood** [kelvinlockwood/kelvinlockw.xyz#38]
We don't have an About page, About needs to be changed to Work.

We're currently linking to the Work page from the 'Book me now' button in the footer. (This button should actually link to https://www.buymeacoffee.com/kelvinlockwood/e/24822)

Each Work / Product item is currently 1020 pixels wide (on desktop). I might be better in the region of 900 pixels to fit in with the other content types and be consistent when displayed on this category page...
https://pedantic-sinoussi-3efb9c.netlify.app/tags/ux/

**Comment by MoNouri97** [comment]
should be fixed in the latest build
