### ISSUE TITLE
Services section

### ISSUE THREAD

**Issue by kelvinlockwood** [kelvinlockwood/kelvinlockw.xyz#46]
We're only displaying 3 services but there should be 6 > https://xd.adobe.com/view/8a626811-2fea-419b-5abd-4177a925eb9e-fc53/

I mentioned in #22 this section can be 1040 wide

#37 explains the icons for this section

There are mistakes in the current text, replace with this...

**Customer Development**
Let me help you understand prospective customers and their needs that you may be able to satisfy. You cannot validate your assumptions on your own, I’ll take you through a challenging process where we talk with customers to discover if your assumptions are true.

**Hyper-convenient Design Thinking**
I like to remove things that create friction and distraction and this typically means a shorter route to a solution. Less is often more. Whilst I’m not a graphic designer I do think deeply about the lack of attention span people have when they’re confronted with new products or steps within those products. 

**Marketplace Research**
Rarely is a marketplace as simple as supply and demand. And whilst the internet empowers us to remove middlemen there are always other stakeholders to consider. I can help you figure out the wider ecosystem that your product or marketplace operates in, and if, and how you could fuel adoption.

**Product Architecture**
The requirements are clear but there are many ways for the features and components of your product to fit into the overall system and business model. I take a user-centred approach to map the functions and features you require, to the form of your product.

**Crowdfunding**
There’s nowhere to hide if you launch a crowdfunding campaign unprepared. The eager and eagled-eyed investors will pick apart every word, picture and number in your materials. I’ve had previous success with equity crowdfunding and I can help you get your ducks in a row.

**Pitch Deck Development**
You have a blank canvas to communicate your ideas but you’re struggling to connect the creative side of your brain with the logical side. I can distill your vision and convert your messaging & content into a compelling and flowing narrative.

**Comment by MoNouri97** [comment]
services section is built dynamically , from this file
`https://github.com/kelvinlockwood/kelvinlockw.xyz/blob/main/src/_data/services.js`
its in JSON format

I updated the values but you can change them anytime by editing that file
I also responded/fixed the other issues
